name: Update Version on File Change

on:
  push:
    branches:
      - master

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch all history
      run: git fetch --unshallow

    - name: Check for File Changes
      id: check_changes
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        if [[ $changed_files == *"logger.c"* ]] || [[ $changed_files == *"logger.exe"* ]]; then
          echo "::set-output name=files_changed::true"
        else
          echo "::set-output name=files_changed::false"
        fi

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/Robaa2168/Cscripts.git

        files_changed=${{ steps.check_changes.outputs.files_changed }}
        
        if [[ $files_changed == "true" ]]; then
          # Get the latest tag, if no tags are found, default to v0.0
          latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo 'v0.0')
          major_version=$(echo $latest_tag | cut -d'.' -f1 | tr -d 'v')
          minor_version=$(echo $latest_tag | cut -d'.' -f2)

          # Start a loop to find a tag that does not exist already
          while true; do
            # Increment the minor version
            minor_version=$((minor_version + 1))
            new_tag="v$major_version.$minor_version"

            # Check if tag exists
            if ! git rev-parse $new_tag >/dev/null 2>&1; then
              break
            fi
          done

          git tag $new_tag
          git push --tags
        else
          echo "No relevant files changed. Skipping version update."
        fi


